name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  TestAndCompile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - run: yarn
      - run: yarn test
      - run: yarn compile
